name: taro_card
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.2
  http: ^1.2.0
  url_launcher: ^6.3.2
  firebase_core: ^4.9.0
  firebase_remote_config: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # 这里是我们配置的本地图片路径
  assets:
    - assets/images/