// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl4i-VI2szAY8QdZvbhubvBFL9Ws8s2MQ',
    appId: '1:366428734957:web:d036c41c9f41eb687fd3e4',
    messagingSenderId: '366428734957',
    projectId: 'tai-taro-card',
    authDomain: 'tai-taro-card.firebaseapp.com',
    storageBucket: 'tai-taro-card.firebasestorage.app',
    measurementId: 'G-QCKZGH8PWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhssklvIVh9ReHsTmkitTBYk8Q9omkzFU',
    appId: '1:366428734957:android:4034ea47daf66fe57fd3e4',
    messagingSenderId: '366428734957',
    projectId: 'tai-taro-card',
    storageBucket: 'tai-taro-card.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWY6nhQyCfVklv7pq-8d_QscrGn08nVOU',
    appId: '1:366428734957:ios:2c10c08ad06d089a7fd3e4',
    messagingSenderId: '366428734957',
    projectId: 'tai-taro-card',
    storageBucket: 'tai-taro-card.firebasestorage.app',
    iosBundleId: 'com.example.taroCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWY6nhQyCfVklv7pq-8d_QscrGn08nVOU',
    appId: '1:366428734957:ios:2c10c08ad06d089a7fd3e4',
    messagingSenderId: '366428734957',
    projectId: 'tai-taro-card',
    storageBucket: 'tai-taro-card.firebasestorage.app',
    iosBundleId: 'com.example.taroCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl4i-VI2szAY8QdZvbhubvBFL9Ws8s2MQ',
    appId: '1:366428734957:web:2f7d66b81ebe16657fd3e4',
    messagingSenderId: '366428734957',
    projectId: 'tai-taro-card',
    authDomain: 'tai-taro-card.firebaseapp.com',
    storageBucket: 'tai-taro-card.firebasestorage.app',
    measurementId: 'G-KEZCCN0GL9',
  );
}
